# Generated by Django 5.2.4 on 2025-08-03 11:42

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EPCRecord",
            fields=[
                (
                    "lm_key",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("address1", models.CharField(max_length=255)),
                ("address2", models.CharField(blank=True, max_length=255)),
                ("address3", models.CharField(blank=True, max_length=255)),
                ("postcode", models.CharField(max_length=10)),
                ("property_type", models.CharField(blank=True, max_length=50)),
                ("built_form", models.CharField(blank=True, max_length=50)),
                ("inspection_date", models.DateField(blank=True, null=True)),
                (
                    "total_floor_area",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("number_habitable_rooms", models.IntegerField(blank=True, null=True)),
                ("number_heated_rooms", models.IntegerField(blank=True, null=True)),
                ("uprn", models.CharField(blank=True, db_index=True, max_length=100)),
                ("full_address", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="LandRegistrySale",
            fields=[
                (
                    "unique_id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("price_paid", models.IntegerField()),
                ("deed_date", models.DateField()),
                ("postcode", models.CharField(max_length=10)),
                ("property_type", models.CharField(max_length=1)),
                ("new_build", models.CharField(max_length=1)),
                ("estate_type", models.CharField(max_length=1)),
                ("transaction_category", models.CharField(max_length=1)),
                ("saon", models.CharField(blank=True, max_length=100)),
                ("paon", models.CharField(blank=True, max_length=100)),
                ("street", models.CharField(blank=True, max_length=255)),
                ("locality", models.CharField(blank=True, max_length=100)),
                ("town", models.CharField(blank=True, max_length=100)),
                ("district", models.CharField(blank=True, max_length=100)),
                ("county", models.CharField(blank=True, max_length=100)),
                ("linked_data_uri", models.URLField(blank=True)),
                ("num_bedrooms", models.IntegerField(blank=True, null=True)),
                ("square_footage", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PropertyProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("postcode", models.CharField(max_length=10)),
                ("paon", models.CharField(blank=True, max_length=100)),
                ("street", models.CharField(blank=True, max_length=255)),
                ("number_habitable_rooms", models.IntegerField(blank=True, null=True)),
                ("square_footage", models.IntegerField(blank=True, null=True)),
                (
                    "estimated_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("ons_lsoa", models.CharField(blank=True, max_length=20)),
                ("rightmove_listing_id", models.CharField(blank=True, max_length=50)),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, geography=True, null=True, srid=4326
                    ),
                ),
                (
                    "epc_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="land_registry.epcrecord",
                    ),
                ),
                (
                    "land_registry_sale",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="land_registry.landregistrysale",
                    ),
                ),
            ],
        ),
    ]
