# Generated by Django 5.2.4 on 2025-08-03 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('land_registry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landregistrysale',
            name='linked_data_uri',
        ),
    ]
