# Generated by Django 5.2.4 on 2025-08-04 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_registry', '0002_remove_landregistrysale_linked_data_uri'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyprofile',
            name='number_habitable_rooms',
        ),
        migrations.AddField(
            model_name='propertyprofile',
            name='estimated_num_bedrooms',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
