# Generated by Django 5.2.4 on 2025-08-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_registry', '0003_remove_propertyprofile_number_habitable_rooms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landregistrysale',
            name='full_address',
            field=models.CharField(blank=True, db_index=True, max_length=256, null=True),
        ),
    ]
