# Generated by Django 5.2.4 on 2025-08-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_registry', '0004_landregistrysale_full_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landregistrysale',
            name='num_bedrooms',
        ),
        migrations.RemoveField(
            model_name='landregistrysale',
            name='square_footage',
        ),
        migrations.AddField(
            model_name='propertyprofile',
            name='price_per_sq_ft',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertyprofile',
            name='price_per_sq_metre',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
