# Generated by Django 5.2.4 on 2025-08-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("sheet_url", models.URLField(blank=True)),
                (
                    "sheet_file",
                    models.FileField(blank=True, null=True, upload_to="spreadsheets/"),
                ),
            ],
        ),
    ]
