# Generated by Django 5.2.4 on 2025-08-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="brochure_file",
            field=models.FileField(blank=True, null=True, upload_to="brochures/"),
        ),
        migrations.AddField(
            model_name="project",
            name="brochure_title",
            field=models.CharField(
                blank=True, default="Sales Brochure", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="brochure_url",
            field=models.URLField(blank=True),
        ),
    ]
