# Generated by Django 5.2.4 on 2025-08-12 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_project_brochure_file_project_brochure_title_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="allowed_investors",
            field=models.ManyToManyField(
                blank=True, related_name="allowed_projects", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="ProjectAccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ALLOWED", "Allowed"), ("DENIED", "Denied")],
                        max_length=10,
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=100)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("path", models.CharField(max_length=255)),
                ("ts", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["project", "ts", "status"],
                        name="projects_pr_project_4f6850_idx",
                    )
                ],
            },
        ),
    ]
