# Generated by Django 5.2.4 on 2025-08-21 05:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_allowed_investors_projectaccesslog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='allowed_investors',
            field=models.ManyToManyField(blank=True, help_text='Users who can view this project’s page', related_name='allowed_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
