services:
  db:
    image: postgis/postgis:15-3.3
    environment:
      POSTGRES_DB: devdb
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - ../../data:/data:ro
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: property_development.settings.dev

    depends_on:
      - db
    env_file:
      - .env.dev

volumes:
  postgres_data:
