version: '3.9'

services:
  db:
    image: postgis/postgis:15-3.3
    environment:
      POSTGRES_DB: prod_db
      POSTGRES_USER: prod_user
      POSTGRES_PASSWORD: prod_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: docker/prod/Dockerfile
    command: gunicorn property_development.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: property_development.settings.prod
    depends_on:
      - db
    env_file:
      - .env.prod

volumes:
  postgres_data:
