# ruff.toml (repo root)

# --- Python file discovery / project layout ---
# See: include/exclude/src docs.
# Ruff treats these as the Python files to lint.
include = ["**/*.py"]
# Honor .gitignore by default; add project-specific ignores here:
extend-exclude = [
  ".venv", "venv", "node_modules", "dist", "build",
]

# If your source lives outside the repo root, list it here so import
# resolution and some rules behave better.
src = ["."]
# If you have namespace packages, enable:
# namespace-packages = true

# Target the Python you run in Docker/CI.
target-version = "py313"

line-length = 120

[lint]
# Keep the defaults strict; add what you like.
select = ["E", "F", "I", "UP", "B"]
# Example: let Black handle long lines if you prefer
# ignore = ["E501"]

# Per-file rule relaxations.
[lint.per-file-ignores]
# Django settings often import-with-star or re-export names;
# allow: F401 (unused imports), F403 (import *), F405 (starred names used)
"property_development/settings/base.py" = ["F401"]
"property_development/settings/dev.py"  = ["F401", "F403", "F405"]
"property_development/settings/prod.py" = ["F401", "F403", "F405"]

# Django migrations: keep them linted, but don’t fight autogenerated code.
"**/migrations/*.py" = ["E501", "F401", "F403", "F405"]

# manage.py: optionally silence input-path warning in some setups
# "manage.py" = ["INP001"]